apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: kamaji
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: kamaji
  egress:
    - toEntities:
        - kube-apiserver
    - toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
  ingress:
  - fromEntities:
    - cluster
    - kube-apiserver
