diff --git a/helm/kamaji/charts/kamaji-crds/templates/kamaji.clastix.io_kubeconfiggenerators.yaml b/helm/kamaji/charts/kamaji-crds/templates/kamaji.clastix.io_kubeconfiggenerators.yaml
index dd9b96f..e61dfe8 100644
--- a/helm/kamaji/charts/kamaji-crds/templates/kamaji.clastix.io_kubeconfiggenerators.yaml
+++ b/helm/kamaji/charts/kamaji-crds/templates/kamaji.clastix.io_kubeconfiggenerators.yaml
@@ -3,6 +3,7 @@ kind: CustomResourceDefinition
 metadata:
   annotations:
     cert-manager.io/inject-ca-from: {{ include "kamaji-crds.certManagerAnnotation" . }}
+    helm.sh/resource-policy: keep
   labels:
     {{- include "kamaji-crds.labels" . | nindent 4 }}
   name: kubeconfiggenerators.kamaji.clastix.io
