apiVersion: v2
appVersion: edge-25.12.3
description: Kamaji is the Hosted Control Plane Manager for Kubernetes.
home: https://github.com/giantswarm/kamaji-app
icon: https://s.giantswarm.io/app-icons/kamaji/1/light.png
kubeVersion: ">=1.21.0-0"
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
name: kamaji
sources:
- https://github.com/clastix/kamaji
type: application
version: 0.2.0
dependencies:
- name: kamaji-crds
  version: 0.2.0
annotations:
  io.giantswarm.application.team: "rocket"
  io.giantswarm.application.audience: "giantswarm"
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.upstream-chart-url: "https://github.com/clastix/kamaji"
  io.giantswarm.application.upstream-chart-version: "edge-25.12.3"
