apiVersion: v2
appVersion: edge-25.12.3
description: Kamaji is the Hosted Control Plane Manager for Kubernetes.
home: https://github.com/giantswarm/kamaji-app
icon: https://github.com/clastix/kamaji/raw/master/assets/logo-colored.png
kubeVersion: ">=1.21.0-0"
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
name: kamaji
sources:
- https://github.com/clastix/kamaji
type: application
version: null
dependencies:
- name: kamaji-etcd
  repository: https://clastix.github.io/charts
  version: ">=0.11.0"
  condition: kamaji-etcd.deploy
- name: kamaji-crds
  version: null
annotations:
  io.giantswarm.application.team: "rocket"
  io.giantswarm.application.audience: "giantswarm"
  io.giantswarm.application.managed: "true"
