apiVersion: v2
appVersion: edge-25.12.3
description: Kamaji is the Hosted Control Plane Manager for Kubernetes.
home: https://github.com/giantswarm/kamaji-app
icon: https://github.com/clastix/kamaji/raw/master/assets/logo-colored.png
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
name: kamaji-crds
sources:
  - https://github.com/clastix/kamaji
type: application
version: 0.0.1
annotations:
  io.giantswarm.application.team: "rocket"
  io.giantswarm.application.audience: "giantswarm"
  io.giantswarm.application.managed: "true"
